### ISSUE TITLE
Errors after running `npm run dist`

### ISSUE THREAD

**Issue by jezpoz** [Altinn/DesignSystem#254]
Using this package for another of Brønnøysunds projects. When installing the npm package, and including `style.dist.portal.min.css` file to our React app, the CSS file references files that are not in the dist-folder (and one `../../images/brick_pattern.svg` file which is supposed to be `../images/brick_pattern.svg`). 

But it references a Content-folder which is not in the dist-folder. Not in the npm package, or when I have cloned this repo and run `npm run dist`.

**Comment by matsgm** [comment]
Resolving this issue by creating a unique CSS for the specified project.
