### ISSUE TITLE
Lenke mangler?

### ISSUE THREAD

**Issue by gunnium** [Altinn/DesignSystem#61]
På denne siden: https://altinn.github.io/designsystem-styleguide/komigang/prosjektet.html under punkt 4: skal det være en lenke på "Kom i gang som designer" til denne https://altinn.github.io/designsystem-styleguide/komigang/designere.html?

Gratulerer med ny drakt, Altinn!

**Comment by mrosvik** [comment]
Takk for beskjed! Lenken er nå fikset :)
